export const FETCH_BOOKS_REQUEST = 'FETCH_BOOKS_REQUEST';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAILURE = 'FETCH_BOOKS_FAILURE';
export const BOOK_DELETED_FROM_CART = 'BOOK_DELETED_FROM_CART';
export const BOOK_ADDED_TO_CART = 'BOOK_ADDED_TO_CART';
export const FILTER_BOOKS_BY_TEXT = 'FILTER_BOOKS_BY_TEXT';
export const FILTER_BOOKS_BY_CATEGORY = 'FILTER_BOOKS_BY_CATEGORY';